#################################################################################
# Usage:
# mkdir -p ${HOME}/bundle && \
# podman run -it --rm --pull always \
#     --volume ${HOME}/bundle:/root/bundle:z \
#   quay.io/cloudctl/koffer:latest bundle --silent \
#     --config https://codectl.io/docs/config/nightlies/sparta.yml

tpdk:
  version: 0.12

platform:
  openshift:
    version: 4.6.4

provider:
  aws: {}

koffer:
  silent: false
  mirror: localhost:5000
  plugins:
    cloudctl:
      version: master
      service: github.com
      organization: cloudctl
    openshift-iac:
      version: master
      service: github.com
      organization: codesparta
    collector-ocp:
      version: master
      service: github.com
      organization: codesparta
