koffer:
  silent: true
  plugins:
    sparta:
      version: master
      service: github.com
      organization: codesparta
      env:
        - name: "BUNDLE"
          value: "true"
        - name: "MIRROR"
          value: "true"
        - name: "PROVIDER"
          value: "aws"
        - name: "VERSION"
          value: "latest"
        - name: "TPDK_VERSION"
          value: "master"
        - name: "SPARTA_VERSION"
          value: "master"
        - name: "REDHAT_OPERATORS"
          value: "null"
        - name: "RHCOS_AWS"
          value: "true"
