provider:
  aws:
    region: us-gov-west-1
    publish: internal
    key_id: sdfASDFasdf
    priv key: asdfASDFasdf

platform:
  tanzu:
    version: 1.1.9

koffer:
  silent: false
  mirror: localhost:5000
  plugins:
    cloudctl:
      version: master
      service: github.com
      organization: containercraft
    openshift:
      version: master
      service: github.com
      organization: codesparta
    collector-infra:
      version: master
      service: github.com
      organization: codesparta
