koffer:
  silent: false
  plugins:
    cloudctl:
      version: master
      service: github.com
      organization: containercraft
    openshift:
      version: master
      service: github.com
      organization: codesparta
    collector-infra:
      version: master
      service: github.com
      organization: codesparta
