provider:
  aws:
    region: us-gov-west-1
    publish: internal
    key_id: sdfASDFasdf
    priv key: asdfASDFasdf

platform:
  openshift:
    version: 4.6.1

koffer:
  silent: false
  mirror: localhost:5000
  plugins:
    cloudctl:
      version: master
      service: github.com
      organization: cloudctl
    openshift-iac:
      version: master
      service: github.com
      organization: codesparta
    collector-ocp:
      version: master
      service: github.com
      organization: codesparta
