koffer:
  silent: false
  plugins:
    openshift:
      version: 4.5.14
      service: github.com
      organization: codesparta
    collector-infra:
      version: master
      service: github.com
      organization: codesparta
