koffer:
  silent: false
  plugins:
    cloudctl:
      version: v00.21.0128
      service: github.com
      organization: cloudctl
    sparta:
      version: v00.21.0128
      service: github.com
      organization: codesparta
    collector-ocp:
      version: v00.21.0202
      service: github.com
      organization: codesparta

#################################################################################
# Usage:
#
# mkdir -p ${HOME}/bundle && \
# podman run -it --rm --pull always \
#     --volume ${HOME}/bundle:/root/bundle:z \
#   quay.io/cloudctl/koffer:latest bundle --silent \
#     --config https://codectl.io/docs/config/stable/sparta.yml
#
#################################################################################
