# podman run -it --rm --pull always --volume ${HOME}/bundle:/root/bundle:z quay.io/cloudctl/koffer bundle --config https://codectl.io/docs/config/nightlies/sparta.yml 
koffer:
  silent: false
  plugins:
    sparta:
      version: v00.21.0521
      service: github.com
      organization: codesparta
      env:
        - name: "BUNDLE"
          value: "true"
        - name: "MIRROR"
          value: "true"
        - name: "VERSION"
          value: "latest-4.7"
        - name: "PROVIDER"
          value: "aws"
        - name: "RHCOS_AWS"
          value: "true"
        - name: "TPDK_VERSION"
          value: "4.7.9"
        - name: "SPARTA_VERSION"
          value: "v00.21.0521"
        - name: "REDHAT_OPERATORS"
          value: "null"
